services:
  ac-db-import:
    image: ${DOCKER_IMAGE_PREFIX:-acore/ac-wotlk}-db-import:${DOCKER_IMAGE_TAG:-master}

  ac-worldserver:
    image: ${DOCKER_IMAGE_PREFIX:-acore/ac-wotlk}-worldserver:${DOCKER_IMAGE_TAG:-master}

  ac-authserver:
    image: ${DOCKER_IMAGE_PREFIX:-acore/ac-wotlk}-authserver:${DOCKER_IMAGE_TAG:-master}

  ac-client-data-init:
    image: ${DOCKER_IMAGE_PREFIX:-acore/ac-wotlk}-client-data:${DOCKER_IMAGE_TAG:-master}

  ac-tools:
    image: ${DOCKER_IMAGE_PREFIX:-acore/ac-wotlk}-tools:${DOCKER_IMAGE_TAG:-master}

  ac-dev-server:
    image: ${DOCKER_IMAGE_PREFIX:-acore/ac-wotlk}-dev-server:${DOCKER_IMAGE_TAG:-master}
